package mstimezone

// ianaAliasesToWindows contains CLDR Windows zone aliases for Windows IDs supported by windowsToIANA.
var ianaAliasesToWindows = map[string]string{
	"africa/abidjan":                 "greenwich standard time",
	"africa/accra":                   "greenwich standard time",
	"africa/addis_ababa":             "e. africa standard time",
	"africa/algiers":                 "w. central africa standard time",
	"africa/asmera":                  "e. africa standard time",
	"africa/bamako":                  "greenwich standard time",
	"africa/bangui":                  "w. central africa standard time",
	"africa/banjul":                  "greenwich standard time",
	"africa/bissau":                  "greenwich standard time",
	"africa/blantyre":                "south africa standard time",
	"africa/brazzaville":             "w. central africa standard time",
	"africa/bujumbura":               "south africa standard time",
	"africa/ceuta":                   "romance standard time",
	"africa/conakry":                 "greenwich standard time",
	"africa/dakar":                   "greenwich standard time",
	"africa/dar_es_salaam":           "e. africa standard time",
	"africa/djibouti":                "e. africa standard time",
	"africa/douala":                  "w. central africa standard time",
	"africa/el_aaiun":                "morocco standard time",
	"africa/freetown":                "greenwich standard time",
	"africa/gaborone":                "south africa standard time",
	"africa/harare":                  "south africa standard time",
	"africa/kampala":                 "e. africa standard time",
	"africa/kigali":                  "south africa standard time",
	"africa/kinshasa":                "w. central africa standard time",
	"africa/libreville":              "w. central africa standard time",
	"africa/lome":                    "greenwich standard time",
	"africa/luanda":                  "w. central africa standard time",
	"africa/lubumbashi":              "south africa standard time",
	"africa/lusaka":                  "south africa standard time",
	"africa/malabo":                  "w. central africa standard time",
	"africa/maputo":                  "south africa standard time",
	"africa/maseru":                  "south africa standard time",
	"africa/mbabane":                 "south africa standard time",
	"africa/mogadishu":               "e. africa standard time",
	"africa/monrovia":                "greenwich standard time",
	"africa/ndjamena":                "w. central africa standard time",
	"africa/niamey":                  "w. central africa standard time",
	"africa/nouakchott":              "greenwich standard time",
	"africa/ouagadougou":             "greenwich standard time",
	"africa/porto-novo":              "w. central africa standard time",
	"africa/tunis":                   "w. central africa standard time",
	"america/anguilla":               "sa western standard time",
	"america/antigua":                "sa western standard time",
	"america/argentina/la_rioja":     "argentina standard time",
	"america/argentina/rio_gallegos": "argentina standard time",
	"america/argentina/salta":        "argentina standard time",
	"america/argentina/san_juan":     "argentina standard time",
	"america/argentina/san_luis":     "argentina standard time",
	"america/argentina/tucuman":      "argentina standard time",
	"america/argentina/ushuaia":      "argentina standard time",
	"america/aruba":                  "sa western standard time",
	"america/bahia_banderas":         "central standard time (mexico)",
	"america/barbados":               "sa western standard time",
	"america/belem":                  "sa eastern standard time",
	"america/belize":                 "central america standard time",
	"america/blanc-sablon":           "sa western standard time",
	"america/boa_vista":              "sa western standard time",
	"america/boise":                  "mountain standard time",
	"america/buenos_aires":           "argentina standard time",
	"america/cambridge_bay":          "mountain standard time",
	"america/campo_grande":           "central brazilian standard time",
	"america/catamarca":              "argentina standard time",
	"america/cayman":                 "sa pacific standard time",
	"america/chihuahua":              "central standard time (mexico)",
	"america/ciudad_juarez":          "mountain standard time",
	"america/coral_harbour":          "sa pacific standard time",
	"america/cordoba":                "argentina standard time",
	"america/costa_rica":             "central america standard time",
	"america/coyhaique":              "magallanes standard time",
	"america/creston":                "us mountain standard time",
	"america/curacao":                "sa western standard time",
	"america/danmarkshavn":           "greenwich standard time",
	"america/dawson_creek":           "us mountain standard time",
	"america/detroit":                "eastern standard time",
	"america/dominica":               "sa western standard time",
	"america/edmonton":               "mountain standard time",
	"america/eirunepe":               "sa pacific standard time",
	"america/el_salvador":            "central america standard time",
	"america/fort_nelson":            "us mountain standard time",
	"america/fortaleza":              "sa eastern standard time",
	"america/glace_bay":              "atlantic standard time",
	"america/godthab":                "greenland standard time",
	"america/goose_bay":              "atlantic standard time",
	"america/grenada":                "sa western standard time",
	"america/guadeloupe":             "sa western standard time",
	"america/guayaquil":              "sa pacific standard time",
	"america/guyana":                 "sa western standard time",
	"america/hermosillo":             "us mountain standard time",
	"america/indiana/knox":           "central standard time",
	"america/indiana/marengo":        "us eastern standard time",
	"america/indiana/petersburg":     "eastern standard time",
	"america/indiana/tell_city":      "central standard time",
	"america/indiana/vevay":          "us eastern standard time",
	"america/indiana/vincennes":      "eastern standard time",
	"america/indiana/winamac":        "eastern standard time",
	"america/indianapolis":           "us eastern standard time",
	"america/inuvik":                 "mountain standard time",
	"america/iqaluit":                "eastern standard time",
	"america/jamaica":                "sa pacific standard time",
	"america/jujuy":                  "argentina standard time",
	"america/juneau":                 "alaskan standard time",
	"america/kentucky/monticello":    "eastern standard time",
	"america/kralendijk":             "sa western standard time",
	"america/lima":                   "sa pacific standard time",
	"america/louisville":             "eastern standard time",
	"america/lower_princes":          "sa western standard time",
	"america/maceio":                 "sa eastern standard time",
	"america/managua":                "central america standard time",
	"america/manaus":                 "sa western standard time",
	"america/marigot":                "sa western standard time",
	"america/martinique":             "sa western standard time",
	"america/matamoros":              "central standard time",
	"america/mazatlan":               "mountain standard time (mexico)",
	"america/mendoza":                "argentina standard time",
	"america/menominee":              "central standard time",
	"america/merida":                 "central standard time (mexico)",
	"america/metlakatla":             "alaskan standard time",
	"america/moncton":                "atlantic standard time",
	"america/monterrey":              "central standard time (mexico)",
	"america/montserrat":             "sa western standard time",
	"america/nassau":                 "eastern standard time",
	"america/nome":                   "alaskan standard time",
	"america/noronha":                "utc-02",
	"america/north_dakota/beulah":    "central standard time",
	"america/north_dakota/center":    "central standard time",
	"america/north_dakota/new_salem": "central standard time",
	"america/ojinaga":                "central standard time",
	"america/panama":                 "sa pacific standard time",
	"america/paramaribo":             "sa eastern standard time",
	"america/port_of_spain":          "sa western standard time",
	"america/porto_velho":            "sa western standard time",
	"america/puerto_rico":            "sa western standard time",
	"america/rankin_inlet":           "central standard time",
	"america/recife":                 "sa eastern standard time",
	"america/resolute":               "central standard time",
	"america/rio_branco":             "sa pacific standard time",
	"america/santarem":               "sa eastern standard time",
	"america/santo_domingo":          "sa western standard time",
	"america/scoresbysund":           "azores standard time",
	"america/sitka":                  "alaskan standard time",
	"america/st_barthelemy":          "sa western standard time",
	"america/st_kitts":               "sa western standard time",
	"america/st_lucia":               "sa western standard time",
	"america/st_thomas":              "sa western standard time",
	"america/st_vincent":             "sa western standard time",
	"america/swift_current":          "canada central standard time",
	"america/tegucigalpa":            "central america standard time",
	"america/thule":                  "atlantic standard time",
	"america/toronto":                "eastern standard time",
	"america/tortola":                "sa western standard time",
	"america/vancouver":              "pacific standard time",
	"america/winnipeg":               "central standard time",
	"america/yakutat":                "alaskan standard time",
	"antarctica/casey":               "central pacific standard time",
	"antarctica/davis":               "se asia standard time",
	"antarctica/dumontdurville":      "west pacific standard time",
	"antarctica/macquarie":           "tasmania standard time",
	"antarctica/mawson":              "west asia standard time",
	"antarctica/mcmurdo":             "new zealand standard time",
	"antarctica/palmer":              "sa eastern standard time",
	"antarctica/rothera":             "sa eastern standard time",
	"antarctica/syowa":               "e. africa standard time",
	"antarctica/vostok":              "central asia standard time",
	"arctic/longyearbyen":            "w. europe standard time",
	"asia/aden":                      "arab standard time",
	"asia/almaty":                    "west asia standard time",
	"asia/anadyr":                    "russia time zone 11",
	"asia/aqtau":                     "west asia standard time",
	"asia/aqtobe":                    "west asia standard time",
	"asia/ashgabat":                  "west asia standard time",
	"asia/atyrau":                    "west asia standard time",
	"asia/bahrain":                   "arab standard time",
	"asia/bishkek":                   "central asia standard time",
	"asia/brunei":                    "singapore standard time",
	"asia/calcutta":                  "india standard time",
	"asia/dili":                      "tokyo standard time",
	"asia/dushanbe":                  "west asia standard time",
	"asia/famagusta":                 "gtb standard time",
	"asia/gaza":                      "west bank standard time",
	"asia/hong_kong":                 "china standard time",
	"asia/jakarta":                   "se asia standard time",
	"asia/jayapura":                  "tokyo standard time",
	"asia/katmandu":                  "nepal standard time",
	"asia/khandyga":                  "yakutsk standard time",
	"asia/kuala_lumpur":              "singapore standard time",
	"asia/kuching":                   "singapore standard time",
	"asia/kuwait":                    "arab standard time",
	"asia/macau":                     "china standard time",
	"asia/makassar":                  "singapore standard time",
	"asia/manila":                    "singapore standard time",
	"asia/muscat":                    "arabian standard time",
	"asia/nicosia":                   "gtb standard time",
	"asia/novokuznetsk":              "north asia standard time",
	"asia/oral":                      "west asia standard time",
	"asia/phnom_penh":                "se asia standard time",
	"asia/pontianak":                 "se asia standard time",
	"asia/qatar":                     "arab standard time",
	"asia/qostanay":                  "west asia standard time",
	"asia/rangoon":                   "myanmar standard time",
	"asia/saigon":                    "se asia standard time",
	"asia/samarkand":                 "west asia standard time",
	"asia/thimphu":                   "bangladesh standard time",
	"asia/urumqi":                    "central asia standard time",
	"asia/ust-nera":                  "vladivostok standard time",
	"asia/vientiane":                 "se asia standard time",
	"atlantic/bermuda":               "atlantic standard time",
	"atlantic/canary":                "gmt standard time",
	"atlantic/faeroe":                "gmt standard time",
	"atlantic/madeira":               "gmt standard time",
	"atlantic/south_georgia":         "utc-02",
	"atlantic/st_helena":             "greenwich standard time",
	"atlantic/stanley":               "sa eastern standard time",
	"australia/broken_hill":          "cen. australia standard time",
	"australia/lindeman":             "e. australia standard time",
	"australia/melbourne":            "aus eastern standard time",
	"etc/gmt":                        "utc",
	"etc/gmt+1":                      "cape verde standard time",
	"etc/gmt+10":                     "hawaiian standard time",
	"etc/gmt+3":                      "sa eastern standard time",
	"etc/gmt+4":                      "sa western standard time",
	"etc/gmt+5":                      "sa pacific standard time",
	"etc/gmt+6":                      "central america standard time",
	"etc/gmt+7":                      "us mountain standard time",
	"etc/gmt-1":                      "w. central africa standard time",
	"etc/gmt-10":                     "west pacific standard time",
	"etc/gmt-11":                     "central pacific standard time",
	"etc/gmt-14":                     "line islands standard time",
	"etc/gmt-2":                      "south africa standard time",
	"etc/gmt-3":                      "e. africa standard time",
	"etc/gmt-4":                      "arabian standard time",
	"etc/gmt-5":                      "west asia standard time",
	"etc/gmt-6":                      "central asia standard time",
	"etc/gmt-7":                      "se asia standard time",
	"etc/gmt-8":                      "singapore standard time",
	"etc/gmt-9":                      "tokyo standard time",
	"etc/utc":                        "utc",
	"europe/amsterdam":               "w. europe standard time",
	"europe/andorra":                 "w. europe standard time",
	"europe/athens":                  "gtb standard time",
	"europe/belgrade":                "central europe standard time",
	"europe/bratislava":              "central europe standard time",
	"europe/brussels":                "romance standard time",
	"europe/busingen":                "w. europe standard time",
	"europe/copenhagen":              "romance standard time",
	"europe/dublin":                  "gmt standard time",
	"europe/gibraltar":               "w. europe standard time",
	"europe/guernsey":                "gmt standard time",
	"europe/helsinki":                "fle standard time",
	"europe/isle_of_man":             "gmt standard time",
	"europe/jersey":                  "gmt standard time",
	"europe/kiev":                    "fle standard time",
	"europe/kirov":                   "russian standard time",
	"europe/lisbon":                  "gmt standard time",
	"europe/ljubljana":               "central europe standard time",
	"europe/luxembourg":              "w. europe standard time",
	"europe/madrid":                  "romance standard time",
	"europe/malta":                   "w. europe standard time",
	"europe/mariehamn":               "fle standard time",
	"europe/monaco":                  "w. europe standard time",
	"europe/oslo":                    "w. europe standard time",
	"europe/podgorica":               "central europe standard time",
	"europe/prague":                  "central europe standard time",
	"europe/riga":                    "fle standard time",
	"europe/rome":                    "w. europe standard time",
	"europe/san_marino":              "w. europe standard time",
	"europe/sarajevo":                "central european standard time",
	"europe/simferopol":              "russian standard time",
	"europe/skopje":                  "central european standard time",
	"europe/sofia":                   "fle standard time",
	"europe/stockholm":               "w. europe standard time",
	"europe/tallinn":                 "fle standard time",
	"europe/tirane":                  "central europe standard time",
	"europe/ulyanovsk":               "astrakhan standard time",
	"europe/vaduz":                   "w. europe standard time",
	"europe/vatican":                 "w. europe standard time",
	"europe/vienna":                  "w. europe standard time",
	"europe/vilnius":                 "fle standard time",
	"europe/zagreb":                  "central european standard time",
	"europe/zurich":                  "w. europe standard time",
	"indian/antananarivo":            "e. africa standard time",
	"indian/chagos":                  "central asia standard time",
	"indian/christmas":               "se asia standard time",
	"indian/cocos":                   "myanmar standard time",
	"indian/comoro":                  "e. africa standard time",
	"indian/kerguelen":               "west asia standard time",
	"indian/mahe":                    "mauritius standard time",
	"indian/maldives":                "west asia standard time",
	"indian/mayotte":                 "e. africa standard time",
	"indian/reunion":                 "mauritius standard time",
	"pacific/efate":                  "central pacific standard time",
	"pacific/enderbury":              "utc+13",
	"pacific/fakaofo":                "utc+13",
	"pacific/funafuti":               "utc+12",
	"pacific/galapagos":              "central america standard time",
	"pacific/gambier":                "utc-09",
	"pacific/guam":                   "west pacific standard time",
	"pacific/kosrae":                 "central pacific standard time",
	"pacific/kwajalein":              "utc+12",
	"pacific/majuro":                 "utc+12",
	"pacific/midway":                 "utc-11",
	"pacific/nauru":                  "utc+12",
	"pacific/niue":                   "utc-11",
	"pacific/noumea":                 "central pacific standard time",
	"pacific/pago_pago":              "utc-11",
	"pacific/palau":                  "tokyo standard time",
	"pacific/pitcairn":               "utc-08",
	"pacific/ponape":                 "central pacific standard time",
	"pacific/rarotonga":              "hawaiian standard time",
	"pacific/saipan":                 "west pacific standard time",
	"pacific/tahiti":                 "hawaiian standard time",
	"pacific/tarawa":                 "utc+12",
	"pacific/truk":                   "west pacific standard time",
	"pacific/wake":                   "utc+12",
	"pacific/wallis":                 "utc+12",
}
